CREATE TABLE tbFoo (
	id UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT PK_Foo PRIMARY KEY NONCLUSTERED
		CONSTRAINT DF_Foo_Id DEFAULT NEWID(),
	MyOid dbo.CLR_Oid NOT NULL
)
GO

INSERT INTO tbFoo (MyOid) VALUES('47cc67093475061e3d95369d')

SELECT * FROM tbFoo

DROP TABLE tbFoo
GO