CREATE TABLE tbFoo (
	id UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT PK_Foo PRIMARY KEY NONCLUSTERED
		CONSTRAINT DF_Foo_Id DEFAULT NEWID(),
	MyOid BSONOID NOT NULL
		CONSTRAINT DF_Foo_MyOid DEFAULT dbo.ufn_NewOid(0x710790)
)
GO

--INSERT INTO tbFoo (MyOid) VALUES('47cc67093475061e3d95369d')

INSERT INTO tbFoo (id) VALUES (NEWID());
INSERT INTO tbFoo (id) VALUES (NEWID());
INSERT INTO tbFoo (id) VALUES (NEWID());
INSERT INTO tbFoo (id) VALUES (NEWID());
INSERT INTO tbFoo (id) VALUES (NEWID());
INSERT INTO tbFoo (id) VALUES (NEWID());

SELECT * FROM tbFoo

DROP TABLE tbFoo
GO

